//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.15 at 12:23:03 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xml.dongtv.vn/schema/products", 
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
        xmlns = {@XmlNs(prefix = "", namespaceURI = "http://xml.dongtv.vn/schema/products")}

)
package dongtv.dto;

import javax.xml.bind.annotation.XmlNs;

